title: Le Pei
logo: /assets/img/logo.png
description: ✿◕ ‿ ◕✿ 
show_downloads: false
google_analytics: UA-151467678-1
theme: jekyll-theme-minimal
plugins:
  - jemoji
# Disqus Comments
disqus:
    # Leave shortname blank to disable comments site-wide.
    # Disable comments for any post by adding `comments: false` to that post's YAML Front Matter.
    shortname: lepei
