title: Le Pei - Playing Aura Kingdom
logo: /assets/img/logo.png
description: Dedicated to Aura Kingdom, an unique anime-style casual MMORPG. ✿◕ ‿ ◕✿
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
